proyecto_relacion_modelos/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('entradas/', views.lista_entradas, name='lista_entradas'),
    path('', views.index, name='index'),
    path('lista_mario/', views.lista_mario, name='lista_mario'),
    path('lista_ton/', views.lista_ton, name='lista_ton')
]

proyecto_relacion_modelos/proyecto_relacion_modelos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

proyecto_relacion_modelos/blog/models.py
from django.db import models

class Autor(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()

    def __str__(self):
        return self.nombre

class Entrada(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

proyecto_relacion_modelos/blog/views.py
from django.shortcuts import render
from .models import Entrada, Autor

def lista_entradas(request):
    entradas = Entrada.objects.all()
    return render(request, 'blog/lista_entradas.html', {'entradas': entradas})

def index(request):
    return render(request, 'blog/index.html')

def lista_mario(request):
     # Obtiene el objeto Autor relacionado con el nombre "Mario Vargas Llosa"
    autor_mario_vargas_llosa = Autor.objects.get(nombre="Mario Vargas Llosa")

    # Filtra las entradas por el autor "Mario Vargas Llosa"
    entradas = Entrada.objects.filter(autor=autor_mario_vargas_llosa)

    return render(request, 'blog/lista_entradas.html', {'entradas': entradas})

def lista_ton(request):
    autor_ton_cruise = Autor.objects.get(nombre="Ton Cruise")
    entradas = Entrada.objects.filter(autor=autor_ton_cruise )
    return render(request, 'blog/lista_entradas.html', {'entradas': entradas})

proyecto_relacion_modelos/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    <style>
        .btn-custom {
            background-color: #D2E48F;
            color: #000; /* Cambia el color del texto si es necesario */
        }
    </style>
    <title>Botones con Bootstrap</title>
</head>
<body class="text-center">
    <div class="container mt-5">
        <h1>Selecciona una página:</h1>
        <div class="row mt-5">
            <div class="col">
                <a href="/blog/lista_mario" class="btn btn-custom btn-lg">Mario Vargas</a>
            </div>
            <div class="col">
                <a href="/blog/lista_ton" class="btn btn-custom btn-lg">Ton Cruise</a>
            </div>
            <div class="col">
                <a href="/blog/entradas" class="btn btn-custom btn-lg">Todas las entradas</a>
            </div>
        </div>
    </div>
</body>
</html>

proyecto_relacion_modelos/blog/templates/blog/lista_entradas.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de Entradas</title>
</head>
<body>
    <h1>Lista de Entradas</h1>
    <ul>
        {% for entrada in entradas %}
            <li>
                <h2>{{ entrada.titulo }}</h2>
                <p>{{ entrada.contenido }}</p>
                <p>Autor: {{ entrada.autor }}</p>
                <p>Fecha de Publicación: {{ entrada.fecha_publicacion }}</p>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'blog:index' %}">Ir al Inicio</a>
</body>
</html>